# Generated by Django 5.2 on 2025-04-13 10:56

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='CatPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat_per', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'catPersons',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commune', models.CharField(max_length=4)),
                ('name_commune', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0xxxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(default='0xxxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('fax', models.CharField(default='034xxxxxx', max_length=9, validators=[django.core.validators.RegexValidator(message='Fax number must be 9 digits.', regex='^\\d{9}$')])),
                ('rip', models.CharField(max_length=20)),
                ('email', models.EmailField(default='gmail@gmail.com', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.catpersonnel')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FicheStockSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('observation', tinymce.models.HTMLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('name_fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='FicheStockEntr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('number', models.CharField(max_length=10)),
                ('source', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('observation', tinymce.models.HTMLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('name_fiche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='DemandClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('name_demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.product')),
            ],
        ),
    ]
