# Generated by Django 5.2 on 2025-04-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='cat_person',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='commune',
        ),
        migrations.DeleteModel(
            name='CatPersonnel',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
