# Generated by Django 5.2 on 2025-07-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockApp', '0002_remove_personnel_cat_person_remove_personnel_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
