# Generated by Django 5.2 on 2025-04-16 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat_per', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'catPersons',
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_commune', models.CharField(max_length=4)),
                ('name_commune', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0xxxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(default='0xxxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('fax', models.CharField(default='034xxxxxx', max_length=9, validators=[django.core.validators.RegexValidator(message='Fax number must be 9 digits.', regex='^\\d{9}$')])),
                ('rip', models.CharField(max_length=20)),
                ('email', models.EmailField(default='gmail@gmail.com', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalApp.catpersonnel')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonalApp.commune')),
            ],
        ),
    ]
