# Generated by Django 5.2 on 2025-04-16 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='cat_person',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='commune',
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_french', models.CharField(max_length=50)),
                ('name_arabic', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('nin', models.CharField(max_length=18)),
                ('phone', models.CharField(default='0900000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('rip', models.CharField(default='00799999', max_length=20)),
                ('grade', models.CharField(max_length=100)),
                ('email', models.EmailField(default='gmail@gmail.com', max_length=50)),
                ('observation', models.TextField(max_length=500)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chargers', to='PersonalApp.commune')),
                ('commune_birth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commune_birth_charger', to='PersonalApp.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Delegue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_french', models.CharField(max_length=50)),
                ('name_arabic', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('nin', models.CharField(max_length=18)),
                ('phone', models.CharField(default='0900000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('rip', models.CharField(default='00799999', max_length=20)),
                ('grade', models.CharField(max_length=100)),
                ('email', models.EmailField(default='gmail@gmail.com', max_length=50)),
                ('observation', models.TextField(max_length=500)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegues', to='PersonalApp.commune')),
                ('commune_birth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegues_birth', to='PersonalApp.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_french', models.CharField(max_length=50)),
                ('name_arabic', models.CharField(max_length=50)),
                ('date_birth', models.DateField()),
                ('nin', models.CharField(max_length=18)),
                ('phone', models.CharField(default='0900000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('rip', models.CharField(default='00799999', max_length=20)),
                ('grade', models.CharField(max_length=100)),
                ('email', models.EmailField(default='gmail@gmail.com', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField(max_length=500)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='PersonalApp.commune')),
                ('commune_birth', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions_birth', to='PersonalApp.commune')),
            ],
        ),
        migrations.CreateModel(
            name='SG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_french', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0900000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('fax', models.CharField(default='034000000', max_length=9, validators=[django.core.validators.RegexValidator(message='Fax number must be 9 digits.', regex='^\\d{9}$')])),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PersonalApp.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_french', models.CharField(max_length=50)),
                ('phone', models.CharField(default='0900000000', max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits.', regex='^\\d{10}$')])),
                ('fax', models.CharField(default='034000000', max_length=9, validators=[django.core.validators.RegexValidator(message='Fax number must be 9 digits.', regex='^\\d{9}$')])),
                ('nin', models.CharField(max_length=18)),
                ('rip', models.CharField(default='00799999', max_length=20)),
                ('email', models.EmailField(default='gmail@gmail.com', max_length=50)),
                ('recruitment', models.DateTimeField()),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PersonalApp.commune')),
            ],
        ),
        migrations.DeleteModel(
            name='CatPersonnel',
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
