# Generated by Django 5.2 on 2025-07-27 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0002_remove_personnel_cat_person_remove_personnel_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sg',
            name='fix',
            field=models.CharField(blank=True, default='034000000', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Fax number must be 9 digits.', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='sg',
            name='fax',
            field=models.CharField(blank=True, default='034000000', max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Fax number must be 9 digits.', regex='^\\d{9}$')]),
        ),
    ]
