# Generated by Django 5.2 on 2025-07-27 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonalApp', '0003_sg_fix_alter_sg_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='name_arabic',
            field=models.CharField(default='غير معروف', max_length=80),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='name_french',
            field=models.CharField(max_length=80),
        ),
    ]
